# Generated by Django 2.2.11 on 2020-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
